from tkinter import *

def haromszogterulet(masterwindow):
    def calc(*args):
        a = alengthscan.get()
        b = malengthscan.get()
        res = (int(a) * int(b)) / 2
        results.delete(0, END)
        results.insert(0, str(res))
    haromszogt = Toplevel(masterwindow, height=400, width=600)
    haromszogt.title("Python SPAR projekt")
    haromszogt.minsize(width = 600, height = 400)
    haromszogt.maxsize(width = 600, height = 400)
    selection = IntVar()
    selection.set(1)
    alengthscan = StringVar()
    malengthscan = StringVar()
    menusor = Frame(haromszogt, width=600, height=400, bd=10, highlightbackground="green", highlightthickness=10)
    menusor.pack(side = TOP, fill = X)
    menu1 = Menubutton(menusor, text = "Főoldal", underline = 0, bg="#EC4949", width=15, height=2)
    menu1.pack(side = LEFT)
    dashboard = Menu(menu1,tearoff="off")
    menu1.config(menu = dashboard)
    menu3 = Menubutton(menusor, text = "Benzin számító", underline = 0,bg="#EC4949", width=15, height=2)
    menu3.pack(side = LEFT)
    likes = Menu(menu3, tearoff="off")
    likes  .add_command(label = "Benzin", underline = 0, background="#EC4949")
    likes.add_command(label = "Diesel", underline = 0,background="#EC4949")
    menu3.config(menu = likes)
    menu2 = Menubutton(menusor, text = "Adószámító", underline = 0,bg="#EC4949", width=15, height=2)
    menu2.pack(side = LEFT)
    views = Menu(menu2, tearoff="off")
    views.add_command(label = "Adószámító", underline = 0, background="#EC4949")
    views.add_command(label = "Kenyérszámító", underline = 0,background="#EC4949")
    menu2.config(menu =views)
    menu4 = Menubutton(menusor, text = "Spar", underline = 0,bg="#EC4949", width=15, height=2)
    menu4.pack(side = LEFT)
    uploads = Menu(menu4 ,tearoff="off")
    uploads.add_command(label = "Hőmérséklet váltó", underline = 0, background="#EC4949")
    uploads.add_command(label = "Pénznem váltó", underline = 0,background="#EC4949")
    uploads.add_command(label = "Mértékegység váltó", underline = 0,background="#EC4949")
    uploads.add_command(label = "Terület/Kerület", underline = 0, background="#EC4949")
    uploads.add_command(label = "URL rövidítő", underline = 0,background="#EC4949")
    uploads.add_command(label = "Jelszó erősség",  underline = 0,background="#EC4949")
    menu4.config(menu = uploads)
    menu5 = Menubutton(menusor, text = "Játékok", underline = 0,bg="#EC4949", width=15, height=2)
    menu5.pack(side = LEFT)
    videos = Menu(menu5,tearoff="off")
    videos.add_command(label = "Színes játék", underline = 0, background="#EC4949")
    videos.add_command(label = "Vízesés modell quiz", underline = 0,background="#EC4949")
    menu5.config(menu = videos)
    menu6 = Menubutton(menusor, text = "Kilépés", underline = 0,bg="#EC4949", width=15, height=2)
    menu6.pack(side = LEFT)
    videos = Menu(menu6,tearoff="off", )
    videos.add_command(label = "Kilépés", command = haromszogt.destroy, underline = 0,background="#EC4949")
    menu6.config(menu = videos)
    ize2=Label(haromszogt, text="Sponsored by SPAR ™", fg="green",font=('Silkscreen', 8))
    ize2.place(x=30,y=350)
    can1 = Canvas(haromszogt, width=10, height=10)
    photo = PhotoImage(file='python-project\képek\spar-logo-1.png')
    item = can1.create_image(20, 20, image = photo)
    can1.place(x=150,y=350)

    textbox = Label(haromszogt, text="Háromszög Terület", fg="green")
    a = Label(haromszogt, text="a", fg="green")
    alength = Entry(haromszogt, textvariable=alengthscan, width=35)
    alength.focus()
    b = Label(haromszogt, text="b", fg="green")
    malength = Entry(haromszogt, textvariable=malengthscan, width=35)
    alengthscan.trace_add("write", calc)
    malengthscan.trace_add("write", calc)
    results = Entry(haromszogt, width=35)
    resulttext = Label(haromszogt, text="Eredmény:", fg="green")

    b.place(x=62, y=175)
    malength.place(x=95,y=175)
    alength.place(x=95, y=145)
    a.place(x=62, y=145)
    textbox.place(x=95, y=115)
    results.place(x=95, y=230)
    resulttext.place(x=12, y=230)
